table:
  name: payout_settings
  schema: public
insert_permissions:
  - role: member
    permission:
      check:
        user_id:
          _eq: X-Hasura-User-Id
      columns:
        - eth_wallet_address
        - user_id
select_permissions:
  - role: member
    permission:
      columns:
        - eth_wallet_address
        - user_id
      filter:
        user_id:
          _eq: X-Hasura-User-Id
  - role: od_payer
    permission:
      columns:
        - eth_wallet_address
        - user_id
      filter: {}
update_permissions:
  - role: member
    permission:
      columns:
        - eth_wallet_address
      filter:
        user_id:
          _eq: X-Hasura-User-Id
      check:
        user_id:
          _eq: X-Hasura-User-Id
